# Generated by Django 4.0.2 on 2022-11-28 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubication', models.CharField(choices=[('main_menu', 'Main Menu'), ('left_sidebar', 'Let Sidebar'), ('right_sidebar', 'Right Sidebar'), ('tree_menu', 'Tree Menu'), ('up_menu', 'Up Menu'), ('bottom_menu', 'Bottom Menu')], default='main_menu', max_length=20)),
                ('label', models.CharField(max_length=20)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('father', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_menu', to='mySecondAplication.menu')),
            ],
            options={
                'ordering': ['ubication', 'label', 'weight', 'status'],
            },
        ),
    ]
