# Generated by Django 4.0.2 on 2022-11-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySecondAplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
