# Generated by Django 4.0.2 on 2022-11-28 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySecondAplication', '0002_alter_menu_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='father',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_menu', to='mySecondAplication.menu'),
        ),
    ]
